name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x gradlew
          fi

      - name: Fix KSP and Gradle settings
        run: |
          echo "ksp.incremental=false" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED" >> gradle.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon -Dksp.incremental=false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quran-app-debug
          path: app/build/outputs/apk/debug/*.apk
